---
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Documentation'
    label: 'documentation'
change-template: '- $TITLE, by @$AUTHOR (#$NUMBER)'
template: |
  # What's changed

  $CHANGES
