---
namespace: lablabs
name: wireguard
version: "0.3.1"
readme: README.md
authors:
  - Labyrinth Labs <info@lablabs.io>
description: Wireguard Server Ansible Collection.
license_file: LICENSE
tags: [wireguard, vpn, system, linux, security, networking]
dependencies:
  devsec.hardening: "7.12.0"
  robertdebock.roles: "1.9.7"
repository: https://github.com/lablabs/ansible-collection-wireguard
documentation: https://github.com/lablabs/ansible-collection-wireguard
homepage: https://www.lablabs.io
issues: https://github.com/lablabs/ansible-collection-wireguard/issues
