---
namespace: lablabs
name: wireguard
version: "0.3.3"
readme: README.md
authors:
  - Labyrinth Labs <info@lablabs.io>
description: Wireguard Server Ansible Collection.
license_file: LICENSE
tags: [wireguard, vpn, system, linux, security, networking]
dependencies:
  devsec.hardening: "8.7.0"
  robertdebock.roles: "1.10.6"
repository: https://github.com/lablabs/ansible-collection-wireguard
documentation: https://github.com/lablabs/ansible-collection-wireguard
homepage: https://www.lablabs.io
issues: https://github.com/lablabs/ansible-collection-wireguard/issues
