---
- name: Add WireGuard repository
  get_url:
    url: "{{ wireguard_repo_url }}"
    dest: /etc/yum.repos.d/wireguard.repo

- name: Install EPEL repository
  yum:
    name: epel-release
    update_cache: true

- name: Install required packages
  yum:
    name: "{{ wireguard_distro_packages }}"
    state: present
  tags:
    - wg-install
