---
- name: Add WireGuard repository
  ansible.builtin.get_url:
    url: "{{ wireguard_repo_url }}"
    dest: /etc/yum.repos.d/wireguard.repo
    mode: '0644'

- name: Install EPEL repository
  ansible.builtin.yum:
    name: epel-release
    update_cache: true

- name: Install required packages
  ansible.builtin.yum:
    name: "{{ wireguard_distro_packages }}"
    state: present
  tags:
    - wg-install
