---
- name: Install GPG - required to add wireguard key
  apt:
    name: "{{ wireguard_distro_packages }}"
    state: present

- name: Add WireGuard repository on buster or earlier
  apt_repository:
    repo: "deb http://deb.debian.org/debian buster-backports main"
    state: present
    update_cache: true
  when: ansible_distribution_version | int <= 10
  tags:
    - wg-install
