---
- name: Add wireguard COPR
  yum_repository:
    name: "jdoss-wireguard"
    description: "Copr repo for wireguard owned by jdoss"
    baseurl: "{{ wireguard_repo_url }}/fedora-$releasever-$basearch/"
    gpgkey: "{{ wireguard_repo_url }}/pubkey.gpg"
    gpgcheck: true

- name: Force yum update
  command: yum makecache    # noqa command-instead-of-module
  changed_when: false

- name: Install required packages
  yum:
    name: "{{ wireguard_distro_packages }}"
    state: present
  tags:
    - wg-install
