---
- name: Add wireguard COPR
  yum_repository:
    name: "jdoss-wireguard"
    description: "Copr repo for wireguard owned by jdoss"
    baseurl: "{{ wireguard_repo_url }}/fedora-$releasever-$basearch/"
    gpgkey: "{{ wireguard_repo_url }}/pubkey.gpg"
    gpgcheck: true

- name: Install required packages
  yum:
    name: "{{ wireguard_distro_packages }}"
    update_cache: true
    state: present
  tags:
    - wg-install