---
- name: Install EPEL repository
  dnf:
    name: epel-release
    update_cache: true

- name: Install ELREPO repository
  dnf:
    name: elrepo-release
    update_cache: true

- name: Install required packages
  dnf:
    name: "{{ wireguard_distro_packages }}"
    state: present
  tags:
    - wg-install
