---
- name: Add WireGuard repository
  ansible.builtin.apt_repository:
    repo: "{{ wireguard_repo_url }}"
    state: present
  when: wireguard_repo_url
  tags:
    - wg-install

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ wireguard_distro_packages }}"
    update_cache: true
    state: present
  tags:
    - wg-install
