---
_system_arch_map:
  i386: '386'
  x86_64: 'amd64'

_system_arch: "{{ _arch_map[ansible_architecture] | default(ansible_architecture) }}"

_wireguard_interface_addr: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask }}"
