---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install Prereqs
      package:
        name: iproute
      when: ansible_os_family == 'RedHat'
    - name: Re-read network facts
      setup:
        gather_subset:
          - '!all'
          - '!any'
          - network
      when: ansible_os_family == 'RedHat'
  roles:
    - wireguard
  vars:
    wireguard_dir: /data/wireguard
    wireguard_address: 10.214.214.0/24
    wireguard_download_clients: true
    wireguard_download_serverkeys: true
    wireguard_same_keys: true
    wireguard_additional_routes:
      - 172.11.0.0/16
      - 172.22.0.0/20
      - 172.33.0.0/16
    wireguard_peers:
      - name: user1
        allowed_ip: "10.213.213.2"
        publickey: "YXNhc21hc2Fhc3Npc2FzYXNhc2FzYXNhc2FzYXNhc3N=" # Fake Pub Key
      - name: user2
        allowed_ip: "10.213.213.3/32"
        publickey: "YXNhc21hc2Fhc3Npc2FzYXNhc2FzYXNhc2FzYXNhc3N=" # Fake Pub Key
        keepalive: 30
      - name: user3
        allowed_ip: "10.213.213.50/30"
        publickey: "YXNhc21hc2Fhc3Npc2FzYXNhc2FzYXNhc2FzYXNhc3N=" # Fake Pub Key
