---
- name: Security hardening
  hosts: '{{target|default("all")}}'
  become: true
  gather_facts: true

  roles:
    - name: devsec.hardening.ssh_hardening
    - name: devsec.hardening.os_hardening
    - name: robertdebock.roles.fail2ban
