---
- name: Wireguard deployment
  hosts: '{{target|default("all")}}'
  become: true
  gather_facts: true

  roles:
    - name: wireguard

  post_tasks:
    - name: Install iptables-persistent
      apt:
        name:
          - iptables
          - iptables-persistent
        state: present
        update_cache: true

    - name: Setup MASQUERADE for server access through vpn server
      iptables:
        chain: POSTROUTING
        jump: MASQUERADE
        table: nat
        source: "{{ wireguard_address }}"
        out_interface: "{{ wireguard_out_interface }}"

    - name: Save current state of the firewall in system file
      community.general.iptables_state:
        state: saved
        path: /etc/iptables/rules.v4

    - name: Setup ipv4 IP forward
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: true
        state: present
        reload: true
