---
name: Ansible Lint

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Molecule for Ansible
      uses: robertdebock/molecule-action@2.7.2
      with:
        command: lint
