# yamllint disable
---
name: Molecule test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'roles/wireguard/**'
      - 'molecule/wireguard/**'
      - '.github/workflows/**'
  workflow_dispatch:
  schedule:
      - cron: '0 1 1 * *'

jobs:
  standalone:
    name: Test Wireguard Ansible Role
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        config:
          - image: "rockylinux8"
            tag: "latest"
          - image: "ubuntu2004"
            tag: "latest"
          - image: "ubuntu2204"
            tag: "latest"
    steps:
      - name: Fix Git safe directories issue when in containers
        # cf: https://github.com/actions/checkout/issues/760
        run: git config --global --add safe.directory /__w/ansible-collection-wireguard/ansible-collection-wireguard

      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"

      - name: Molecule for Ansible
        uses: robertdebock/molecule-action@4.0.9
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}

      - name: Upload configs
        uses: actions/upload-artifact@v3
        with:
          name: client-configs
          path: clients/
          retention-days: 1
