---
name: pre-commit

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2

    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3
