---
name: Release Drafter

permissions:
  contents: write
  pull-requests: read

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: RELEASE_DRAFTER.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
